name: Release and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or your default branch)

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history for semantic-release

      # Step 2: Set up Node.js with the correct version (Node.js >=20.8.1)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Ensure you're using Node.js 20 or higher

      # Step 3: Install dependencies (including semantic-release and plugins)
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Semantic Release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # GitHub token for authentication
        run: npx semantic-release

  build-and-push:
    needs: release  # Ensures that this step runs only after the release step completes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Version from Package.json
        id: get_version
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }} -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
