name: Release and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Set execute permission for semantic-release
        run: chmod +x node_modules/.bin/semantic-release

      - name: Run Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Debug - Check Git Tags After Release
        run: git tag --list | tail -5

  build-and-push:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug - List Files
        run: ls -la

      - name: Debug - Check package.json
        run: cat package.json || echo "package.json not found!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Version from Git Tags
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Debug - Show Extracted Version
        run: echo "Exracted Version:${{ env.VERSION }}"
      

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest -f ./Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:${{ env.VERSION }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
